version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - hash_db
      - s3_db
      - redis_hash
      - redis_s3
    networks:
      - app-network

  hash_db:
    image: postgres:latest
    container_name: hash_db
    environment:
      POSTGRES_DB: hash_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - app-network

  s3_db:
    image: postgres:latest
    container_name: s3_db
    environment:
      POSTGRES_DB: s3_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - app-network

  redis_s3:
    image: redis:latest
    container_name: redis_s3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_hash:
    image: redis:latest
    container_name: redis_hash
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6377:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge